### ISSUE TITLE
Feature request: basic Mobbr support (400€ pledged)

### ISSUE THREAD

**Issue by patricksavalle** [q2a/question2answer#173]
Mobbr is a payment system for social collaboration. For this QA it means that every Q2A question now becomes payable. When questions are still open, any payment to a question could be crowdfunded and, as soon as the question is closed the money would be divided among all participants based on the voting ratio.  

See what happens when you put this Q2A question (check the Mobbr button!)...
http://fastmovingtargets.nl/workforce/13/amro-dienst-persoonlijke-data-managen-uitdaging-doorbreken

...into our system:
https://mobbr.com/#/task/aHR0cDovL2Zhc3Rtb3Zpbmd0YXJnZXRzLm5sL3dvcmtmb3JjZS8xMy9hbXJvLWRpZW5zdC1wZXJzb29ubGlqa2UtZGF0YS1tYW5hZ2VuLXVpdGRhZ2luZy1kb29yYnJla2Vu/script

We would like to have very basic Mobbr support. 

**This feature is completely generic, it could be used by many other plugins and tools very easily.**
1. Each question page should have the metatag described here: https://github.com/mobbr/mobbr-api-v1/tree/master/specifications#page-scripts-inline Check the HTML of this Mobbr enabled Q2A site: http://fastmovingtargets.nl/workforce/653/odeon-de-spiegel-hoe-ziet-het-theater-van-de-toekomst-eruit 
2. A special URL for resolving usernames, can have any scheme as long as the username is the last segment and it returns the email address of the user. Can also be the normal profile page URL that returns the email address when a specific header is present in the request.  The alternative could be an API method/web-service. This is what we use to connect to Stackexchange, see:
   https://mobbr.com/#/task/aHR0cHM6Ly9zdGFja292ZXJmbG93LmNvbS9xdWVzdGlvbnMvMjcyNTYzNzcvYy12aWV3LXR5cGVzLXBhc3MtYnktY29uc3Qtb3ItYnktdmFsdWU=/script

We think adding this support could help bring the whole Q2A proposition to a professional audience.

*_Please let us know what you think, we have pledged €400 to this issue, which will be divided among all contributors based on Github contributor statistics. Check here: https://mobbr.com/#/task/aHR0cHM6Ly9naXRodWIuY29tL3EyYS9xdWVzdGlvbjJhbnN3ZXIvaXNzdWVzLzE3Mw== *_

**Comment by svivian** [comment]
OK I understand what you're asking for, but I don't think it's really feasible for Q2A.

Firstly there is a key difference between Q2A and Stack Exchange: SE own and control all of their sites. With Q2A each site is owned by someone different so clearly they will all have different opinions regarding outside access to their content.

(By the way, what you suggest about "resolving usernames" to get back email addresses is never going to happen since that's a significant privacy breach.)

Many Q2A sites are on shared hosting so wouldn't be able to handle the hits. Most users would restrict or turn off the API and then you're back to square one with individual sites choosing whether to participate.

This is not to say an API is a terrible idea. I do see the value in it, but I still feel it's more suited to a plugin that site owners opt into.

**Comment by patricksavalle** [comment]
Ok fair, enough.

Then we will just wait for an API plugin ;)

(Our customer edit the .htaccess to restrict resolving username to our server only, so there is no privacy breach)
