### ISSUE TITLE
404 not found in some links

### ISSUE THREAD

**Issue by Goback** [q2a/question2answer#214]
Hi,
I'm getting not found error in some of my pages, like:
http://www.hesabdar94.ir/index.php?qa-rewrite=9/%D9%85%D8%A7%D9%84%DB%8C%D8%A7%D8%AA-%D8%B9%D9%85%D9%84%DA%A9%D8%B1%D8%AF-%DA%86%DB%8C%D8%B3%D8%AA%D8%9F

when i remove "index.php?qa-rewrite=" from it link is ok,
here is my .htaccess content:
```
DirectoryIndex index.php
<IfModule mod_rewrite.c>
RewriteEngine On
#RewriteBase /

RewriteCond %{REQUEST_URI} ^(.*)//(.*)$
RewriteRule . %1/%2 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ index.php?qa-rewrite=$0&%{QUERY_STRING} [L]
</IfModule>
<IfModule mod_rewrite.c>
#Force www:
RewriteEngine On
RewriteCond %{HTTP_HOST} !^www\.
RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]
</IfModule>
```

**Comment by svivian** [comment]
Where is that URL (the `index.php?qa-rewrite=` one) coming from? You have the first URL structure set on your site so that URL shouldn't be linked anywhere.

**Comment by Goback** [comment]
this comes from Google webmaster crawler error! maybe from sitemap.xml that submitted in Google webmaster,I'm getting many 404 errors for that

**Comment by Goback** [comment]
when i open the url from the other browser for the first time without www, 404 appeared and when i enter that address again ,browser resolve the url correctly.
```
first time => http://hesabdar94.ir/sitemap.xml goes to => http://www.hesabdar94.ir/index.php?qa-rewrite=sitemap.xml
second time=> http://hesabdar94.ir/sitemap.xml goes to http://www.hesabdar94.ir/sitemap.xml
```

**Comment by svivian** [comment]
If they are in Webmaster Tools then they are probably old URLs (maybe you had the other URL structure on your site originally?)

The sitemap issue is because you are first requesting the non-www version of the site, `http://hesabdar94.ir` which redirects to `http://www.hesabdar94.ir`. The "second time" you are actually requesting `http://www.hesabdar94.ir/sitemap.xml`, not `http://hesabdar94.ir/sitemap.xml`

So this sounds like a server configuration issue rather than a bug in Q2A. If you're still having problems I suggest asking on the Q2A site for help: http://www.question2answer.org/qa/

**Comment by Goback** [comment]
Thanks.
http://www.question2answer.org/qa/44815/404-not-found-in-some-links
