### ISSUE TITLE
Problem with Facebook login

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#223]
I have setup everything right and the Facebook app status is green. But as I try to login with facebook login then a popup window opens and ask me my facebook credentials and then I hit login. After this nothing happens and the page just reloads.

I tried to ask this in Q2A Q&A but no one has answered over this that's why I am taking it as an issue. It would be great if you could help.

**Comment by svivian** [comment]
I think there are some issues with the FB login. If I am already logged in to Facebook and visit my site, it gets stuck in a redirect loop.

The version of the Facebook SDK we're using is deprecated and no longer supported, so I don't know if there will be a way to fix the problem. But the newest version requires PHP 5.4+ which only 34% of current Q2A sites are using, so that's probably not an option either...

**Comment by gurjyot** [comment]
So what do you suggest us to do?
Q2A Facebook login is having issues and open login plugin is no more supported. This way we are just loosing some good users for our websites. 

It is always good to have three top social network logins on a community website and if those are not on website then it surely affects the registrations. Many of my users have suggested me to have social logins but I don't know what to do now.
But still thanks for your time... :)

**Comment by svivian** [comment]
Did you sign up for the Facebook app recently? I think the problem is you can't register for apps using the old system any more, my test version I set up a few months ago says "v2.1" is the oldest I can use.

I'm still looking into this to see if there is a way around it. If we can't get the old one to work we can still create a new plugin that people can use.

**Comment by svivian** [comment]
Also, are you doing this on a live server, or on localhost?

**Comment by gurjyot** [comment]
Yes I have recently made a Facebook app (just a month back). 
I am using it on a live server. 

If by chance you decide to make a new plugin then adding twitter and Google plus logins will be great idea. (It'll give much hype to Q2A if it is served with inbuilt social logins).

**Comment by svivian** [comment]
Did you try going to facebook.com directly and logging out? That fixes the issue when using the Question2Answer site for me.

**Comment by gurjyot** [comment]
The issue that's happening with me is, when I try to login with Facebook login on my site then after submitting the login form details, the page just reloads and nothing happens. But if I open Facebook on a different tab then I am logged into my Facebook account. 

The submitting of login form actually doesn't save any value for that users in database table as well.

**Comment by gurjyot** [comment]
Sorry for this issue, it was due to Q2A Registration plugin. I have removed the plugin and now Facebook login works fine. But it would be good if you could update the plugin's code and would also introduce Twitter and Google+ logins. I am saying this because support for open login plugin is no more available and it is not compatible to SnowFlat theme any more.
