### ISSUE TITLE
Bug: When user register then after submitting the form he is redirected to homepage

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#242]
As a user register, then he is redirected to homepage and he never gets to know that an confirmation mail has been sent to him.
Means, the message which tell a user to confirm the email is not being shown. Please fix this.

**Comment by svivian** [comment]
The notice does show when you have the option "All new users must confirm their email" ticked. However, in that situation it shows the notice and nothing else on the page - no questions or anything (even though you can still see those by logging out!)

I think when you have the option "Request confirmation of user emails" ticked, it makes sense to show the notice after they first register. But not on every page, because there may be plenty of actions that don't actually require email confirmation.

Will look into fixing this.

**Comment by gurjyot** [comment]
I was trying to fix another issue but eventually this issue also got fixed. "q2a-registeration-blocker" plugin was messing with my website. Now if someone registers then is logged in and can see that "email confirmation" notice. 
The issue due to which this got fixed is #241
