### ISSUE TITLE
When setting another home page, meta tag description is not outputted

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#267]
When setting a different path for the main page in qa-config.php: 

	$QA_CONST_PATH_MAP=array(
		'activity' => ''
	);

the meta description is not displayed anymore on the startpage.

The problem should be in qa-include/pages/default.php - this part:

	if ( (!$explicitqa) && (!$countslugs) && qa_opt('show_home_description') )
		$qa_content['description']=qa_html(qa_opt('home_description'));

**Comment by svivian** [comment]
Unfortunately it doesn't look like this is possible. The meta description is set in `pages/default.php` but if you set a different page as your home page, that file is never called, it goes straight to `pages/activity.php`.

I thought about moving the description into the `qa_content_prepare` function but that's not possible either because by the time we get there, the page has already been set to "activity" and there's no way to tell this is the home page.

**Comment by svivian** [comment]
OK found a way to fix this, now it checks inside `qa_content_prepare` if we're on the home page so it works whatever page is set as the home page.
