### ISSUE TITLE
Feature Request: configurable questions default sort

### ISSUE THREAD

**Issue by michaeltisi** [q2a/question2answer#289]
Would be great to have the ability to configure which sorting method was the default (Recent, Hot, Most Votes, etc.) Would be great to have the home page configurable as well.

**Comment by svivian** [comment]
The home page is configurable using the `$QA_CONST_PATH_MAP` option. See [this question](http://www.question2answer.org/qa/47112/it-is-possible-to-translate-the-url) for more details. You can also use a function override plugin to change the `qa_page_routing` function, that should solve your sorting method issue.

(P.S. the Github issue tracker here is intended for bug reports rather than feature requests. In future, I suggest you open a thread on the [Q2A site](http://www.question2answer.org/qa/) for discussion. Thanks.)
