### ISSUE TITLE
I can not access user accounts with single sign on

### ISSUE THREAD

**Issue by Krl4** [q2a/question2answer#293]
I am using the last version of q2a. with sso.

When I try to access any user account, I get to the page: page not found.

Has this something to do with single sign on? I mean, a user can access his user account if the qa site uses single sign on.

Thanks for your help

**Comment by svivian** [comment]
What are you using for the user accounts? Is this the built-in Wordpress integration or a custom one for another system? Have you followed all the instructions in qa-external-users.php? Do you have the htaccess set up correctly?

**Comment by Krl4** [comment]
Hello there, thanks for replying. It's a custom integration. I followed all the instructions. The htaccess is ok (appears ok in admin). But when I try to access my user page or another user page, i get the message page not found.

function qa_get_logged_in_user_html is set to default.
$publicusername=$logged_in_user['publicusername'];
return '<a href="'.qa_path_html('user/'.$publicusername).'" class="qa-user-link">'.htmlspecialchars($publicusername).'</a>';

and function qa_get_users_html is set to deault too:
$useridtopublic=qa_get_public_from_userids($userids);

		$usershtml=array();

		foreach ($userids as $userid) {
			$publicusername=$useridtopublic[$userid];

			$usershtml[$userid]=htmlspecialchars($publicusername);

			if ($should_include_link)
				$usershtml[$userid]='<a href="'.qa_path_html('user/'.$publicusername).'" class="qa-user-link">'.$usershtml[$userid].'</a>';
		}

		return $usershtml;


I suppose there is actually a default user page when I'm runing a sso q2a.

Thx for the help

**Comment by svivian** [comment]
Are you able to access the user page with `yoursite.com/qa/index.php?qa=user/USERNAME` (replace USERNAME with your username). If that works then it's likely an issue with htaccess.

Otherwise perhaps there is an issue finding the users in your external database. Ensure that the `qa_get_mysql_user_column_type` function is returning the correct column type, and that `qa_get_userids_from_public` returns the correct userids when you pass in your username(s).

**Comment by svivian** [comment]
Also I just noticed that Example 2 from `qa_get_userids_from_public` is out of date - Q2A now uses the `mysqli_*` functions so you should use `mysqli_query` there. But you would be getting an error if that was the case. You can also use the Q2A functions like `qa_db_query_raw`.

**Comment by svivian** [comment]
Hi @Krl4 did you fix your problem? The only thing I can think of is that you did not implement all the required functions. Maybe take a look at `qa-include/util/external-users-wp.php` for some hints.

I'll close this now since I don't think it's a bug in Q2A. If you have further questions you can ask them on the Q2A site here: http://www.question2answer.org/qa/

**Comment by Krl4** [comment]
Hello Svivian,

I didn´t fix it yet, I'm still investigating...
I'll have a look and when I fix it, I will update this post.

Thx anyway for your help ;)
