### ISSUE TITLE
Clicking "Ask Question" button more than once creates duplicate questions.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#309]
The problem is mainly with slow internet speed, if a user is submitting a question with slow internet speed, then he might click "Ask Question" button twice or thrice. The multiple clicking of that button creates duplicated questions of the original questions.

If there could be applied a restriction that once the button is clicked then it can't be clicked again, that can solve this issue. What do you say about this?

**Comment by svivian** [comment]
When this happens they should get an error saying "your submission appears to be a duplicate". Not sure why that's not the case here.

**Comment by gurjyot** [comment]
That's the problem, instead of showing an error it creates a lot of questions. Even in good internet speed if you try to click multiple times on that button then also it'll generate duplicate questions.

**Comment by svivian** [comment]
OK looks like that duplicate detection is only on answers and comments currently. Definitely makes sense to add this to questions too.

**Comment by amiyasahu** [comment]
But checking a currently posted question against all available questions would be a costlier process . Because if you are comparing the submitted content with all other answers or comments there will not be too many . But comparing with all the questions there may be 1000's . 

It can be possible check the duplicate questions which is posted in last hour only , or something like that . 

Or just disabling the ask button after it is clicked would be also a alternate solution (Only at UI level though) .

**Comment by svivian** [comment]
Yes the case for this is when the user clicks the 'ask question' button several times in a short space. I think we'd just need to check the latest few questions (5 at most).

Disabling the button with JS on click would also be a good idea to add on top of that, since it will prevent extra hits to the server and extra checking. We can add that to all post types - questions, answers, comments, wall posts etc.

**Comment by gurjyot** [comment]
Yes disabling button for multiple hits (for all post-types) would be nice idea and if questions check is also introduced then that will be like honey on icecream... ;)

**Comment by phy25** [comment]
I don't think it is a good idea to directly disable submit button. If the network failed and for some reasons the button is not enabled again, the user won't be able to submit the content again unless backuping the content themselves and refresh the page. That's annoying.

**Comment by Mr-Kumar-Abhishek** [comment]
Uhh.. Why not send an ID to the client for every question they want to ask . And verify that when the post is received by the server . If that ID is already posted reject it ? I am just saying haven't read the whole code of this repo
Sent via Micromax
On 30 Oct 2015 09:22, Phy <notifications@github.com> wrote:I don't think it is a good idea to directly disable submit button. If the network failed and for some reasons the button is not enabled again, the user won't be able to submit the content again unless backuping the content themselves and refresh the page. That's annoying.

**Comment by svivian** [comment]
@phy25 we should be able to check in the ajax function if there is an error and re-enable the button. Or it could be disabled for a limited time only (10s maybe).
