### ISSUE TITLE
Users page design in mobiles is very cluttered.

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#310]
Users page design on mobiles is very bad in SnowFlat. There is not sense of symmetry in that page. See to the pic below.

![users](https://cloud.githubusercontent.com/assets/6462850/10832482/bbd477e0-7eb1-11e5-987d-70c55db62568.png)

It would be much better to have users page something like this.

![users1](https://cloud.githubusercontent.com/assets/6462850/10832503/d0970e04-7eb1-11e5-806d-e17890646ca2.png)
![users2](https://cloud.githubusercontent.com/assets/6462850/10832504/d09d6506-7eb1-11e5-86e2-1b0b62863c24.png)

This design is much better then what we have in Q2A. And if you remove that sidebar in users page (as no one visit users page for having a look at sidebar) then this page will look even better.

**Comment by svivian** [comment]
This is something I plan to do when I can. In 1.7 I added the new "block layout" for ranking pages but didn't get around to implementing it for the SnowFlat theme (ironic since that's the theme that would benefit most from it).

If anyone else wants to tackle this, go ahead! The pull request should be made against the 1.8 branch.

**Comment by yerbol89** [comment]
@amiyasahu help :)

**Comment by amiyasahu** [comment]
Ok , I will take a look @yerbol89

**Comment by amiyasahu** [comment]
@yerbol89 , Done with PR #314
