### ISSUE TITLE
password_hash with bcrypt instead of sha1(salt+password+salt)

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#340]
Are there any plans to move from salted SHA-1 to password_hash and the other password_* functions available in PHP 5.5+ (password_compat from ircmaxell available as polyfill) with the PASSWORD_BCRYPT flag ( + salt + cost )?

**Comment by svivian** [comment]
The problem is that we currently support PHP 5.2, and the polyfill only works from 5.3+.

However, I am planning to add a strategy for this in the next version (1.8). I'll add an extra field to the users table to hold the bcrypt password, then do a version check and if the site is running on 5.3+ migrate each user's password as they log in (and use bcrypt for new user registrations, of course).

At some point in the future we'll drop support for 5.2 and we can migrate the rest of the passwords.

**Comment by DanielRuf** [comment]
Sounds good. This is how I would also do it (extra field and silently convert) like you describe it.

5.2 and some newer 5.* versions of PHP are officially not supported anymore. 5.3 should be at least be used as it supports important cryptography related functions.

If I find the time I can provide some pull request for this.

The field should be binary UTF-8 field with a length of 60.

**Comment by svivian** [comment]
That would be great!

Re PHP versions, the problem is that "official support" unfortunately does not correspond with usage. There's still a significant percentage of sites using PHP 5.2 which we'd like to support - although it looks like that's [dropped off a fair bit](http://w3techs.com/technologies/history_details/pl-php/5) this year. Whenever Q2A 2.0 is released we'll certainly be requiring 5.3+.

**Comment by DanielRuf** [comment]
For PHP 5.3+ include the functions from https://github.com/ircmaxell/password_compat
