### ISSUE TITLE
Update jQuery & CKeditor

### ISSUE THREAD

**Issue by DanielRuf** [q2a/question2answer#363]
jQuery 1.12.0 was released and improved the performance and is the last version to support specific older IE versions.

The 2.x is for all modern browsers and does not support old IE versions anymore.

> jQuery 2.x has the same API as jQuery 1.x, but does not support Internet Explorer 6, 7, or 8.

IE 8 is pretty outdated and not supported anymore on most platforms. So what to choose, 1.x or 2.x?

http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

In the future we can migrate to the new 3.x version as Microsoft has officially ended the support for specific IE versions.

**Comment by svivian** [comment]
Using this issue as a "catch-all" for third-party libraries.

All our third-party libraries are updated shortly before release. There's little point updating until then because a newer version will inevitably be released. I'll update PHPMailer for 1.7.3 since that's a security fix, the rest will go into 1.8.

Regarding jQuery, I think we'll probably stick with the 1.x line for 1.8 and probably update it to 2.x for Q2A 1.9/2.0. Deoending on when those are released it may even be 3.x.

**Comment by DanielRuf** [comment]
Ok. Thanks for the information. Is there some roadmap of the planned features and changes for 1.9/2.0?

**Comment by svivian** [comment]
Not really, it will depend on feature requests from users (we usually open a question on the Q2A forum for that).  [Here is the last roadmap](http://www.question2answer.org/qa/45239/can-we-have-a-road-map-of-q2a-1-8) I wrote, basically anything from there that doesn't make it into 1.8 will be the roadmap for 1.9.

I might run a poll at some point to check that most users are happy to drop IE8 support.
