### ISSUE TITLE
hotness update running slow - performance issue

### ISSUE THREAD

**Issue by amiyasahu** [q2a/question2answer#376]
Just noticed the hotness update query is running slow and locks the database for a while.

This happens when the website have a bigger posts table and more number of concurrent users and the hotness update runs for every new question page load  ( when the `Count the number of question views:` option is enabled ). Can this query be written in a better way ? 

Please find the log captured from /var/lib/mysql/svr-slow.log file. 

``` sql
SET timestamp=1454198461;
UPDATE qa_posts AS x, (SELECT parents.postid, parents.created AS qcreated, COALESCE(MAX(children.created), parents.created) as acreated, COUNT(children.postid) AS acount, parents.netvotes, parents.views FROM qa_posts AS parents LEFT JOIN qa_posts AS children ON parents.postid=children.parentid AND children.type='A' WHERE parents.postid>=31644 AND parents.postid<=31644 AND LEFT(parents.type, 1)='Q' GROUP BY postid) AS a SET x.hotness=(((TO_DAYS(a.qcreated)-734138)*86400.0+TIME_TO_SEC(a.qcreated))*100 + ((TO_DAYS(a.acreated)-734138)*86400.0+TIME_TO_SEC(a.acreated))*100 + (a.acount+0.0)*16000000 + (a.netvotes+0.0)*16000000 + (a.views+0.0+1)*400000), x.views=x.views+1, x.lastviewip=INET_ATON('162.158.130.167') WHERE x.postid=a.postid;
# User@Host: xxx[xxx] @ localhost []
# Query_time: 20.682213  Lock_time: 0.000472 Rows_sent: 0  Rows_examined: 3
```

This part of the code causing this query - 

https://github.com/q2a/question2answer/blob/dev/qa-include/pages/question.php#L406

which sets the `inc_views_postid` key . 

And then here it fires the `qa_db_hotness_update` function .

https://github.com/q2a/question2answer/blob/dev/qa-include/qa-page.php#L390

**Comment by svivian** [comment]
To be clear, is this occurring on every page load? Or only when asking questions?

**Comment by amiyasahu** [comment]
Thank you for addressing @svivian . 

Yes it happens on every page load when the last view ip is different than the current one . 

But does not happen 24*7 . When the server is loaded with more visitors and the query is fired frequently causes latency in mysql query.  And at that time the page appear loading slow.

Please let me know if you need more information.

PS : At high traffic time server have more than 50% of RAM free with 60% of CPU utilization. Out of which 80% - 90% of CPU utilization is caused by MySql.

**Comment by q2apro** [comment]
Sidenote: I do not need the hotness page at all. Would be nice to disable it. However, I need the views count for "most view questions"...

**Comment by gurjyot** [comment]
@q2apro you can disable hotness page in admin section. And still you'll
have most viewed questions as that is in Questions page and not in hotness
page.

**Comment by q2apro** [comment]
I am quite sure that the disabled page (which I have disabled) has no effect on the hotness function.

**Comment by gurjyot** [comment]
Okh, I didn't knew that. If you are right then this should be corrected in
Q2A 1.8

**Comment by svivian** [comment]
I've actually been looking at this function as it needed changes to avoid breaking caching. The views counter uses the same hotness function to update, because views count towards the hotness value. (And by the way, "disabling" the hotness page doesn't actually disable it, only the link is removed. See #29.)

Potentially we could have an option to recalculate hotness on editing only, rather than every page view. That would save a lot of queries. Site admins would need to ensure they run the recalc script in Admin > Stats regularly, so it stays updated.

**Comment by amiyasahu** [comment]
Disabling the view count feature , the hotness does not get disabled , rather this query does not get fired in every unique page view. So this saves the slowness. The hotness will run as usual , but only when some event occurs which is fine. Normally in high traffic websites the read : write ratio is 97 : 3 . So if hotness update runs on the write events then it does not impact much.

**Comment by pupi1985** [comment]
The query looks pretty good to me. Here are my thoughts:

 1. I don't think this query is running slow on its own. I bet there is something going on with that server (shared hosting, maybe?)
 1. The server might be running this query more than it should. If the server is receiving IPv6 requests then each question refresh will trigger this query so many updates will be occurring (I guess this is what we actually have to blame here... try upgrading to 1.8 and see if it fixes the issue)
 1. I tested this locally with a 50K posts table (approx 10K question and 40K answers) and the query finished in 5 milliseconds approx.
 1. The query does have two minor flaws:
     1. `AND LEFT(parents.type, 1) = 'Q'` can actually be removed as parents of answers will always be questions.
     1. The `COUNT` can be removed and use `acount` from the `^posts` table
 1. Anther minor improvement (which I guess it should not have any impact in any modern DBMS, but MySQL always surprises me... and in fact, making the change DOES change the query plan) would be to change the `parents.postid >= # AND parents.postid <= #` into a `parents.postid  BETWEEN # AND #` and, in case both values are the same (which is the most common query run), into a `parents.postid = #`.
 1. Taking concurrency to the next step (and assuming everything will happen atomically) this can be devided into:
     1. A select to fetch the most recent answer date for the given questions (unless you'd like to add a field on the posts table to hold this denormalized value... but I don't like that)
     1. A select to fetch the given question
     1. Process all data in PHP
     1. An update by post ID

Not sure what impact does hotness have in cache (haven't thought of it yet). But it can't be that much. I guess hotness is only really used when displaying questions sorted by hotness. So probably it could be left apart from the cache and that would be OK, particularly because ordering by hotness should be pretty fast.

Although not updating hotness on question views would simplify things very much I'm not sure users are going to like that. I'd double check that server and see if it is actually running slow after the upgrade.

**Comment by amiyasahu** [comment]
Yes AFAIK, the query looks good to me except some minor things. 
The server used on this website was a pretty high end server having more than 64GB of RAM and a good processor. So I dont think the hardware causing the bottleneck. I think too many update requests on the records may be causing the slowness.

**Comment by svivian** [comment]
Just pushed some commits that should help with this: 555873b / d46809f / 788f260 / 80e7ee2

- I integrated @pupi1985's suggestions to improve the SQL query.
- The views increment has been split out of the hotness function, and the hotness calculation is only done if the views were updated (i.e. there was a new unique visitor to that question).
- There's a new option under Admin > Viewing to disable recalculating the hotness on every page view. Note that if you disable it, your hotness scores will become out of date, unless you give views zero importance in your weight settings (bottom of Admin > Lists). But you can always recalculate manually in Admin > Stats at any time.
