### ISSUE TITLE
Remove Services_JSON

### ISSUE THREAD

**Issue by Spudley** [q2a/question2answer#394]
the Q2A codebase contains a vendor library Services_JSON, which is used as a compatibility polyfill when `json_encode()` and `json_decode()` are not defined, ie if the site is running PHP 5.1 or earlier.

However, since Q2A now states that it requires PHP 5.2 or later, I would suggest that this compatibility layer is no longer useful; it's just a waste of space and should be removed from the codebase.

**Comment by svivian** [comment]
Technically Q2A 1.7 does support PHP 5.1. Long story short, the polyfill was in the wrong place in 1.7.0, then fixed in 1.7.1. Gideon put 5.2 on the website originally but hasn't updated it.

However, Q2A 1.8 will be 5.2+ so yes I'll remove it at some point.

**Comment by Spudley** [comment]
Thanks for the reply. That does clarify things :)

(I gotta say though... for 1.8, wouldn't it be sensible to move the min spec up to PHP 5.3 at least? There's no point encouraging people to stick with dangerously obsolete PHP versions. Even 5.3 is long-obsolete now, but I know some servers are still using it... I don't know *anyone* who is still supplying 5.2)

**Comment by svivian** [comment]
I understand what you're saying. When we started v1.8 development last year PHP 5.2 was still quite popular (~20% of PHP installs), so we'll stick with that even though 5.2 has dropped off since. The next version will be 5.3+.

It's a bit of a catch-22. We want to support as many people as possible, but at the same time supporting them may mean they don't upgrade...
