### ISSUE TITLE
Incorrect string value: '::1' for function inet_aton

### ISSUE THREAD

**Issue by donhuvy** [q2a/question2answer#397]
I download from: https://github.com/q2a/question2answer/archive/v1.7.4.zip
use XAMPP (lastest version), MySQL 5.7

This is error information:

```
Database query error 1411

Incorrect string value: '::1' for function inet_aton

INSERT INTO qa_users (created, createip, email, passsalt, passcheck, level, handle, loggedin, loginip) VALUES (NOW(), COALESCE(INET_ATON('::1'), 0), 'donhuvy2014@gmail.com', '9y1jp8znxk45q2zd', UNHEX('3a085e7428fa4c95519a085e7cf634c2e4dfa4ea'), 120, 'administrator', NOW(), COALESCE(INET_ATON('::1'), 0))
```
![bug](https://cloud.githubusercontent.com/assets/1328316/13896955/a76d2334-edd2-11e5-87e1-6e620a7073f2.jpg)

![bug2](https://cloud.githubusercontent.com/assets/1328316/13897702/7e347416-eded-11e5-8e72-3bfa211ad872.jpg)

I think have problem at this line: https://github.com/q2a/question2answer/blob/dev/qa-include/db/users.php#L51

I also try to convert 127.0.0.1 to int value, then insert record manually, but don't success.

**Comment by svivian** [comment]
Looks like your server is using an IPv6 address `::1` on localhost. This should be fixed in the upcoming version of Q2A (1.8) as we recently added IPv6 support and no longer use `INET_ATON`.

However, I am not sure why you're getting an actual error there. I actually had the same thing on my computer too (Macbook) where Apache is using IPv6 for localhost, but I never got the error you're getting. The `INET_ATON` function should just return NULL with unsupported values. There is [no mention in the manual](http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_inet-aton) about errors. Maybe there is a my.conf setting controlling that?

Otherwise, an alternate fix is to change a line in your Apache `httpd.conf` file: where it says `Listen 80` change it to `Listen 127.0.0.1:80` and restart Apache. Now localhost will use IPv4 `127.0.0.1`.

**Comment by zhugw** [comment]
I have met the same error. I installed version 1.7.4. And now I resolved it by changing `Listen 80` change it to Listen `127.0.0.1:80` in `httpd.conf`

**Comment by rlerner** [comment]
This issue still exists in 1.7.4 (I seen it was to be fixed in 8).

zhugw's reply was an easy fix for me, while we're having that issue.
