### ISSUE TITLE
Question2Answer 1.7 - Stored XSS Vulnerability

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#435]
Just bringing this into attention from http://www.question2answer.org/qa/52743/security-wise-how-secure-is-q%26a resp. http://iedb.ir/exploits-2900.html

	###########################

	# Question2Answer 1.7 - Stored XSS Vulnerability

	###########################

	######################################################################
	[+] Title: Script Question2Answer 1.7 - Stored XSS Vulnerability
	[+] Author: s0w
	[+] Tested On Windows & Linux
	[+] Date: 21/03/2015
	[+] Type: Web Application
	[+] Script Download: https://github.com/q2a/question2answer
	[+] Vendor Homepage: http://www.question2answer.org
	[+] Vulnerability in:\qa-include\pages\question.php
	[+] Google Dork : intext:"Powered by Question2Answer"
	#######################################################################

	[+] As shown in the code, the value of 'title' and 'textbody' not filtered
	by 'htmlspecialcharts'
	which cause stored xss and same in data-store in webserver SQL commands
	.

	[+] Exploit :
	1. Browse application in browser ..
	2. Add new question with xss code like alert method ;)
	3. submit the new question to viewers ..
	4. complete next steps as xss in tag,body,title,.. etc ..
	5. Finally submit your Qes ..
	6. Test your target in main page ./index.php ..
	7. Use this in Cookies,alerts, Or TrafficBots :D Have Fun !!

	[+] XSS Pattern can be used: '"<script>alert(/s0w/)</script>
	[+] Demo Video : http://youtu.be/6qy9DXifNiw
	[+] Demo Target :
	http://soualwjoab.com/

	# Discovered By: s0w
	# Contact: fb.me/s0w.egy
	# Mail: s0wxp0c@gmail.com

	To Egyptian Shell team | Sec4ever

	###########################

	# Iranian Exploit DataBase = http://IeDb.Ir [2015-03-25]

	###########################

Has this been fixed?

**Comment by svivian** [comment]
Have you tried it? I'm pretty sure someone posted this a while back and it doesn't work.

**Comment by q2apro** [comment]
Nope, I have not. Maybe someone in this field can do so and give us feedback.

**Comment by Coderx7** [comment]
I asked that question, and hoped to get an answer on that. 
It works on 1.7 but doesnt work on 1.7.4 
my question though is, what do you do to avoid such attacks? 
Did you create this script with security in mind? 
login mechanism seems to be unsafe as well, there is no recaptcha or anything that stops a bot or someone from checking and testing passwords blindly!
There also is this problem that, when some one logs out, and doesnt close the web page, and someone else, clicks on the login(using open connect plugin,) there is no prompt for getting password, and user can easily log in with whomever was logged on before (and logged out!)

**Comment by svivian** [comment]
OK checked into this, the vulnerability is NOT with Q2A, but with a third party plugin. The "Demo Target" URL shown above has some kind of widget plugin at the bottom showing new questions, and the output is not escaped there. Notice that the same question in the question list (#37129) correctly encodes the title like `script>alert(/Please secure your site as soon....`

If anyone knows what that plugin is (if it's a publicly-released one), let me know and I'll suggest a fix to the developer.

To answer @Coderx7 questions:

> Did you create this script with security in mind?

Yes, of course. All content in core Q2A is escaped prior to output. And, of course user input is escaped when being added to the database. Any security issues reported (there have been very few) are fixed asap. Unfortunately we cannot do much about third-party developers writing insecure code, this is no different to the myriad of security flaws in Wordpress plugins.

> login mechanism seems to be unsafe as well, there is no recaptcha or anything that stops a bot or someone from checking and testing passwords blindly!

Not true, there is rate limiting for logins - see the options at the bottom of Admin > Spam in your Q2A.

> There also is this problem that, when some one logs out, and doesnt close the web page, and someone else, clicks on the login(using open connect plugin,) there is no prompt for getting password

Hmm, I'll have to check into this further, but I think that's an issue with the login providers (Google etc). When you log out of a website with a Google account it doesn't log you out of Google. I think that's the same on all websites using social logins.

**Comment by q2apro** [comment]
Great work +1

**Comment by Coderx7** [comment]
Thanks alot. 
By the way I noticed contact us is not protected! I couldnt find any options regarding anti-spam features for it. basically one can send a gazaillion numbers of spam using contact us page! what should I do to get this fixed asap?
any short code or snippet of code so that I can enable recaptha there as well?

**Comment by svivian** [comment]
@Coderx7 see the option "Use captcha on feedback form" in Admin > Spam.

**Comment by Coderx7** [comment]
@svivian : Thanks alot , silly me I missed that .
Good job by the way ;)

**Comment by thierryzoller** [comment]
>And, of course user input is escaped when being added to the database
Are you sure about that ? I found that not to be the case in the latest Q2A version leading to breadcumbs XSS vulnerability as they trust database reads and did not validate.

https://github.com/amiyasahu/q2a-breadcrumbs/issues/24

**Comment by svivian** [comment]
@thierryzoller by "escaped" what I actually meant was protection from SQL injection. So you can't put `; DROP TABLE qa_users` or something as the title and execute SQL. No, HTML is not "escaped" on input, only on output. That's the correct way to do it.

There are functions in Q2A such as `qa_sanitize_html` which will clean up the HTML if you need to output actual HTML (e.g. content from the WYSIWYG editor).

**Comment by thierryzoller** [comment]
In an Issue called "Stored XSS Vulnerability" you reply that you escape for SQL injection? And you assume this is going to be understood by devs the right way?

> That's the correct way to do it.
According to whom, the recommended way to approach this problem is  input validation and contextual output encoding.

"**All content in core Q2A** is escaped prior to output."

**Comment by thierryzoller** [comment]
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md

**Comment by svivian** [comment]
I'm not sure what you're getting at, I think there's some confusion.

> The recommended way to approach this problem is input validation and contextual output encoding.

That's exactly what we do in Q2A. "Validation" in this case is not escaping. For example if someone puts `<b>example</b>` as a question title, it's validated to make sure the title meets the minimum and maximum length requirements, but the HTML is not escaped - those specific characters are stored (instead of `&lt;` for example). Wherever the title is displayed on a page, the content *is* escaped so that it shows up as `<b>example</b>` instead of **example**.

That's the correct way to do it as per your link. See also [here](https://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/) and [here](https://stackoverflow.com/questions/3648430/is-it-a-bad-idea-to-escape-html-before-inserting-into-a-database-instead-of-upon) for why escaping on input is not best practice. Hope that clears it up :)
