### ISSUE TITLE
Increase width of sidebar to at least 300px 

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#474]
I don't know why it is not done from the start but it's important for any website who's main source of income is ads. Wider ads turn out more attention than vertical ads. Moreover, widgets look much better in wider area. Even wordpress and SO offers much wider sidebars.

This will also mean that website will look wider and there will be less wasted space all around.

**Comment by svivian** [comment]
This isn't really possible currently because the design is fluid, so the sidebar is a percentage, not a fixed width. We could increase that for desktop but then it messes up for smaller window sizes (between mobile and desktop). And it makes the main Q&A area cramped.

You can try increasing the width of `.qa-body-wrapper`, over 1220 pixels should get the sidebar around the width you want. Or you may be better off having a 300px ad in the content area (e.g. floated to the right of the question text). It certainly will get more attention there. Also Adsense has responsive ads now, so they will fit whatever size sidebar you have.

**Comment by gurjyot** [comment]
The problem is using responsive ads only. Because of responsive ads, a taller ad shows on sidebar which increase the sidebar length. Instead a proper square add is much more profitable on sidebar but with the current sidebar size it's almost impossible.
