### ISSUE TITLE
register form does not warn that the "anonymous" nickname is reserved

### ISSUE THREAD

**Issue by SuperUserNameMan** [q2a/question2answer#481]
Hi,
version 1.7.4

the register form does not display any warning/error nor block the registration when the new user picks the ``[main/anonymous]`` string as nickname.

this might lead to confusion since it is possible to click the ``anonymous`` nickname to get the list of posts from its IP.

**Comment by svivian** [comment]
Yes that's a fair point. There is also an issue with anonymous users choosing an existing username.

BTW the link to the IP only shows for admins/moderators, not regular users.

**Comment by svivian** [comment]
I've added some options in recent commits that should help with this. Specifically, 5ebb18544729f4065eb2dd56c8c49d77d93b62a1 allows you to set disallowed usernames, and defaults to "anonymous" (or what is set in the site's language file).

Anonymous users choosing existing usernames is difficult to solve because if you have many users it makes it very hard to anonymous users to choose a name! But I added an option to prevent choosing a name (so they always come up as "anonymous").
