### ISSUE TITLE
[Bug-Critical] Current version 1.8 of Q2A is not working for fresh installation.

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#492]
Tried installing latest Q2A version 1.8 on date Feb-08-2017 but still getting below error.

>MySQL query error 1146: Table 'db_q2a.qa_options' doesn't exist - Query: SELECT title, content FROM qa_options

http://question2answer.org/qa/55467/anyone-tried-fresh-installation-latest-version-github-error?show=56175#c56175

Upgrading from v1.7.4 to v1.8 is working fine. see
http://question2answer.org/qa/56130/q2a-testing-team-anyone-interested-to-join?show=56267#c56267

Please look into this issue immediately. Thanks!

**Comment by svivian** [comment]
This is related to the enable/disable plugins feature. Basically Q2A always tries to run as normal, but when a SQL error occurs (e.g. there are no tables because Q2A is not installed) it calls a "fail handler" function which runs the Q2A installer.

In this case however, we're calling `qa_opt()` earlier in the code (to check plugin status), so we end up connecting to the database without a fail handler. So one option would be to make a generic fail handler instead of `qa_page_db_fail_handler` and connect to the database earlier in the code.

However, looking at the code I'm not sure exactly where we can put that. I don't think `qa-base.php` will work since different request types (AJAX/blobs etc) have different fail handlers. Will need to think about it.

**Comment by ProThoughts** [comment]
How about, have a file on the server which lists disabled plugins, and ensure it is editable by the web directory. That file can be read and modified without any access to the database.

Otherwise, a special connection to the database is required to be made, without all of the usual error handling stuff that can be affected by plugins.  This can be done during initialization, after qa_initialize_constants_2().

**Comment by svivian** [comment]
Yes that's a possibility, if we can't find any other way around it. Since we are adding caching in this version we can have one writeable folder that we use for different stuff.

**Comment by ProThoughts** [comment]
That is good idea but please keep cache and this folder separate. Some sites may not use cache feature.

**Comment by svivian** [comment]
What I meant is having a folder like `/storage` that you make writable. Then plugin options may be written to `/storage/plugins.json` and if caching is enabled it would go in `/storage/cache/...` If you're not using the cache feature no caches would be written but the plugin options file can still be edited.

**Comment by svivian** [comment]
This has been fixed in the latest commits on 1.8 branch. Let me know if you encounter any problems @ProThoughts

**Comment by ProThoughts** [comment]
@svivian, great! I will check and update you. thanks!

**Comment by ProThoughts** [comment]
@svivian , it is working now. I dont see any errors for fresh installation. Thanks again!

**Comment by gautambjain** [comment]
I am seeing this issue again with latest fresh 1.8.0 version. Uploaded all files without any changes. Changed config file to point to blank mysql database. Please help.
