### ISSUE TITLE
[Bug] HTML validation with https://validator.w3.org error/warnings for homepage

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#494]
Please see below thread for more details.
http://question2answer.org/qa/56352/html-validation-with-https-validator-w3-org

Thanks!

**Comment by svivian** [comment]
I answered on the Q2A question. Most of the warnings don't matter. I'll look at replacing some of the "visual" attributes (`border="0"` etc) with CSS.

**Comment by ProThoughts** [comment]
Ok thank you.

**Comment by svivian** [comment]
I've fixed most of this. Turns out the schema.org microdata was invalid because parts of it were being used on questions lists when they shouldn't (it's only for individual question pages).

The one thing I haven't removed yet is the uses of `<a name="123"></a>` as they are there for backwards compatibility with old links to specific comments/answers. Whether or not this is a big issue I don't know.
