### ISSUE TITLE
[bug] non approved users are displayed on userpage

### ISSUE THREAD

**Issue by ProThoughts** [q2a/question2answer#530]
If user moderation is enabled by "admin->spam->Enable moderation (approval) of users:" then it should not display that user until it is approved by admin. Currently it is displaying user on users page(q2asite.com/users page) as soon as registered.

User can not post anything on site, which is good but still it should not display him on userpage.

You can try here http://demo18.question2answer.info

**Comment by sama55** [comment]
Probably, it may be due to Gideon's design philosophy. Certainly, there is a concept not to admit unauthorized users as regular users. However, "approval" in Q2A is that the user permits some action, it may not be approval of the user itself. In other words, it is "action approval", not "user approval". There is also a possibility of mere program mistake ...

**Comment by ProThoughts** [comment]
@sama55, agree with you but it should not show user unless approved. It also may be complicated to implement this way, many checks.

**Comment by svivian** [comment]
Looked into this and it's not possible the way the query is currently structured. Plus there are other issues like whether to show them on other user-list pages and how that works with what user levels can view each of those pages. It will just add too much configuration and confusion. Like sama55 said, approval is for action approval not person approval.

One possibility you may want to try is setting a lower `QA_MAX_LIMIT_START` in your config. Your users page will then only go up to a certain number, and new users will be after that and should not be shown. Hope that helps.
