### ISSUE TITLE
when i run on my local server it gives this type error 

### ISSUE THREAD

**Issue by ok360** [q2a/question2answer#541]
�]R���0=�_1�k��Vl����E��8N�Il��ƞl[!���7E՞l�{�f�f�����y�4v�l��E�	���f Fh5�D�+F�Vo�$>[�n��W��#���^݄� 9E����SZ7UȋWMdw�\�����n�t�

**Comment by svivian** [comment]
Which version of Q2A?

Do have the HTML compression option turned on in qa-config.php? Try setting that to false and see if it helps.

**Comment by ok360** [comment]
Q2A latest version i try . ok let me check
thanks for reply

**Comment by pupi1985** [comment]
I have an update on this. Definitely changing the flag fixes it... but it doesn't really mean we're always encoding twice. I've just checked out the 1.8 branch (I had been using 1.7.x for a while now) and a single page refresh on the activity page led to this issue. Checking out v1.7.5 made the site back to life.

After a git bisect I could detect the commit to blame was 6355a05331779b2b30a4fae77244af7fde551f99. I also noted there was a commit today that changed that line but it doesn't change the issue.

I have no plugins/themes installed, I'm using the SnowFlat theme. I just hate output buffering and, as you've been playing with it, I will assume you're better than me at that :) which is the polite way of saying *I'm too lazy to provide a PR*. I'm open to do any additional testing or provide any information about the issue, though. Just ask me.

**Comment by svivian** [comment]
Yes the `ob_clean()` is there because if there is an error after the theme output (e.g. a bad query run from the theme or a plugin) then it messes up the website instead of going to the install handler.

But after some research it looks like the `ob_clean()` call removes the content-encoding header but still sends gzipped content for some reason. One solution is [here](https://stackoverflow.com/questions/43768383/php-ob-startob-gzhandler-with-ob-clean-error) but it's a bit hacky. However I found that using `ob_end_clean()` instead also works. This just gets rid of that output buffer (so turns of gzip if you're using it, which is fine for the install page).

**Comment by pupi1985** [comment]
I can confirm `ob_end_clean()` really fixes the issue :+1:

**Comment by svivian** [comment]
OK hopefully this is solved. If you still have problems, let me know.
