### ISSUE TITLE
Microformat issues - missing:author for guest posts

### ISSUE THREAD

**Issue by q2apro** [q2a/question2answer#580]
Also posted in the q2a forum: http://www.question2answer.org/qa/61471/reporting-q2a-1-8-0-fixes-microformat-issues

I see that guest posts have no "person" attribute (itemprop) and are reported in Google Webmaster Tools as missing (Missing: author, Missing: entry-title). However, not with the structured data testing tools, [example here](https://search.google.com/structured-data/testing-tool?url=https://www.mathelounge.de/65004/problem-des-monats-november-2013-marco-bezahlt-neun-munzen#url=https%3A%2F%2Fwww.mathelounge.de%2F65004%2Fproblem-des-monats-november-2013-marco-bezahlt-neun-munzen), it shows up without errors.

**Comment by svivian** [comment]
There is nothing in the schema that says the author (or any property for that matter) is required. The spec for answers is here: http://schema.org/Answer

However, I found this: https://github.com/schemaorg/schemaorg/issues/1656 which suggests that Google requires certain fields in order to display data in search results... but I don't see anywhere that Google gives that information. Question/Answer is not listed [in their structured data docs](https://developers.google.com/search/docs/guides/intro-structured-data).

So we'll just have to play it by ear. I'll look at adding 'anonymous' users to the structured data, hopefully Google won't complain about that...

**Comment by q2apro** [comment]
Have you checked Google Webmaster for your website? Are the same errors displayed?

**Comment by svivian** [comment]
No, I don't get the same errors because I don't allow anonymous users. So all the posts on my site have the author markup.

**Comment by svivian** [comment]
Looked into this, it's not really possible to do properly without a major refactor. But I've just pushed commit 5bab348 as a quick fix. It duplicates some code but it will do for now.

**Comment by q2apro** [comment]
Thanks, I will try the updated files and report back if the error persists in some weeks.

**Comment by q2apro** [comment]
Here on example: https://search.google.com/structured-data/testing-tool?url=https://www.mathelounge.de/317942/wie-lange-dauert-es-bis-das-flugzeug-abhebt#url=https%3A%2F%2Fwww.mathelounge.de%2F317942%2Fwie-lange-dauert-es-bis-das-flugzeug-abhebt

Comment: 33 item
Answer: 1 item
Person: 1 item

Just wondering why person is listed separately. But guess it's correct. Will report back on any upcoming errors if spotted.

**Comment by svivian** [comment]
You are missing the `QAPage` and `Question` microdata from your page. Might need to double check your theme against `qa-theme-base.php` in case you are overriding some functions like `html()`
