### ISSUE TITLE
Should we support PHP7?

### ISSUE THREAD

**Issue by picasso250** [q2a/question2answer#590]
Maybe a little changes could do it.

**Comment by phy25** [comment]
Of course, please point out. Ref: #540

**Comment by BurninLeo** [comment]
The alternative option would be to cease the project, because within few years there will not be any webservers running PHP 5.

**Comment by picasso250** [comment]
Maybe a few days out, I will start to fix it to 7.0

**Comment by pupi1985** [comment]
There is no need for that. Just use the 1.8 branch and post any issues you see, if any, as many of them have been fixed.

BTW, all of them are just notices or warnings so it it's not a big deal either.

**Comment by picasso250** [comment]
OK, I see, seem it could be closed.

**Comment by svivian** [comment]
Hello, thanks for the interest in Q2A. PHP 7 is in fact already supported - Q2A 1.7 works without issue in PHP 7.0. There are a few PHP Notices on PHP 7.1-7.2 that have been fixed in Q2A 1.8 (and should not be showing on live websites anyway).

The latest version from the dev branch is stable and ready to use (will be released very soon).
