### ISSUE TITLE
Should qa_db_users_recalc_points be overridable?

### ISSUE THREAD

**Issue by pupi1985** [q2a/question2answer#60]
Taking a look at how point calculation works I noticed that there is no way to properly integrate it with any type of plugin but an override. I guess, ideally, there would be a new plugin type to hook any additional point calculation.

However, I still have this doubt. What is the logic applied to make the `qa_db_points_update_ifuser function` overridable and not its recalculation counterpart `qa_db_users_recalc_points`?

I mean, I would have accepted both or none to be overridable but not just one :)

I guess the workaround for plugin developers would be to ask users to perform a custom recalculation after performing the core recalculation, most likely a recalc button in the plugin options. However, it is still quite complex compared to what it would take to override that function.

**Comment by svivian** [comment]
Sorry for the super late reply, only just taking a proper look into this. I think that function is not overridable because it contains a ton of complex SQL so is probably quite fragile. A plugin messing with it could easily screw that up. (The same goes for most of the `qa_db_*` functions - most of the overridable ones are those where a primary use case is to avoid the DB altogether.)

However, if I'm not mistaken all the calculations there are based on the formulas in the `qa_db_points_calculations()` function, which *is* overridable. Does that work for you?
