### ISSUE TITLE
v1.8 is not compatible with SMTP Wordpress plugin

### ISSUE THREAD

**Issue by hebele123** [q2a/question2answer#613]
q2a v1.8 integrated with wordpress with wp-mail-smtp plugin (https://wordpress.org/plugins/wp-mail-smtp/) 

When somebody submits an answer a pop-up with the following message shows up:

> Unexpected response from server - please try again or switch off Javascript

When I deactivate wp-mail-smtp plugin the problem goes away.

I found this in php error log:

> PHP Fatal error:  Cannot declare class PHPMailer, because the name is already in use in 
> {PATH}/qa-include/vendor/PHPMailer/class.phpmailer.php on line 28

**Comment by svivian** [comment]
This is probably due to the fix in 87e8730. I scrapped the autoloader because of problems with PHP 7.2.

**Comment by svivian** [comment]
OK should be fixed in a0a0d32. If you're able to test and confirm those changes work, that would be helpful. You'll need to:

1. Replace `qa-include/vendor/PHPMailer/PHPMailerAutoload.php` with [this file](https://raw.githubusercontent.com/q2a/question2answer/bugfix/qa-include/vendor/PHPMailer/PHPMailerAutoload.php).
2. Replace the 2 `require_once` lines in `qa-include/app/emails.php` with the line

        require_once QA_INCLUDE_DIR . 'vendor/PHPMailer/PHPMailerAutoload.php';

(Changes will be part of Q2A 1.8.1)
