### ISSUE TITLE
Update cKeditor to the latest build

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#624]
cKeditor is fixed for the issue of copy and paste in mobile devices in its latest version. So please update it in Q2A so that we can also enjoy it properly ;)

**Comment by Schoaf** [comment]
Updated to version 4.9.1 . Works like a charm.
Only thing I had to figure out was to set 
`config.filebrowserUploadMethod = 'form';`
see http://www.question2answer.org/qa/63155/wysiwyge-cannot-upload-image-incorrect-server-response?show=63175#a63175

I'd make a pull request but I'm not sure if you want my settings to override the "official" ones...

**Comment by Schoaf** [comment]
I would also suggest to adapt the configuration:

-  I left out 
  - coloring (maybe somebody really needs this)
  - copy-paste (who uses this anyway?)
  - Font (leaving  "Styles" there should be sufficient for a Q&A and makes it more consistent)
  - Expanding the view (if you need that much space it does not fit into a Q&A forum design)
  - Remove text format (redundant as you can just select the normal font style to do the same
- I added
  - Code snippet (would be especially useful for the Q&A main forum.
  - Source code view (because I dont trust these editors and my audience is more technical - you might not want this in the default configuration)

![image](https://user-images.githubusercontent.com/13690603/38233377-a8f9d25e-371a-11e8-8425-1febe779e897.png)

The configured builder link (mono theme!):
http://ckeditor.com/builder/7d678d791df3ef84a32a54f24ab51724
My config.js:
`/**
 * @license Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here.
	// For complete reference see:
	// http://docs.ckeditor.com/#!/api/CKEDITOR.config

	// The toolbar groups arrangement, optimized for two toolbar rows.
	config.toolbarGroups = [
		{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks' ] },
		{ name: 'links', groups: [ 'links' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		{ name: 'document', groups: [ 'mode' ] },
		'/',
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles' ] },
		{ name: 'paragraph2', groups: [ 'align', 'bidi' ] }
	];

	// Remove some buttons provided by the standard plugins, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Save,NewPage,Preview,Print,Templates,Cut,Copy,Paste,PasteText,PasteFromWord,Find,Replace,SelectAll,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CopyFormatting,CreateDiv,BidiLtr,BidiRtl,Language,Anchor,PageBreak,Iframe,ShowBlocks,About,Styles,Font';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;pre';
	
	//needed for image upload to work with Q2A
	config.filebrowserUploadMethod = 'form';

	// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';
	
	config.skin = 'moono';
};`

**Comment by svivian** [comment]
CKEditor has been updated and will be in Q2A 1.8.1. Thanks for the tip about `filebrowserUploadMethod`.

As for the other suggestions, I think what we have is a good balance for what most sites will find useful. BTW the "remove text formatting" is not redundant, it does things differently to changing style to "Normal" (removes all styles, colours, bold etc).
