### ISSUE TITLE
Part of installation fails due to ISAPI and FastCGI settings on IIS server

### ISSUE THREAD

**Issue by gautambjain** [q2a/question2answer#634]
Please review this issue in detail: http://www.question2answer.org/qa/63320/cwqadb-qa_options-doesnt-select-title-content-qa_options?show=63848#a63848

In my opinion it is a critical issue to be addressed.

**Comment by svivian** [comment]
The way you described the issue sounds like it's a problem with the server setup. As I mention in that thread, if you're getting a database problem on FastCGI but not ISAPI it could be something to do with the extensions. Make sure to enable mysqli. Try testing a plain PHP script outside of Q2A that connects to the database and selects some data from a table you know exists.

Unfortunately we don't have the resources to support IIS, only Apache/Nginx on Linux servers. There's no way for me to test and debug. If you are able to find the problem yourself and there is a fix we can implement in the Q2A code I will gladly do so. Otherwise there is nothing I can do about it myself, sorry.
