### ISSUE TITLE
Make it easier for new users to understand how points work

### ISSUE THREAD

**Issue by gturri** [q2a/question2answer#712]
(this is more a feature request than a bug report)

I found out that the users of my site understand that when a user has points it means that he contributed correctly to the site, but that's all. In particular it appears that it's not clear for them:
* how they score points (for instance that on my website getting an upvote brings 10 points and that casting a downvote costs 1 point)
* how it can unlock permissions (for instance that on my website a user need at least 50 points to be able to downvote)

I could add an ad hoc page with all those explanations, but I can think of two features that would improve this:
* It could be nice that users have access to a read-only page that would display nicely the content of the `admin/points` and `admin/permissions` pages
* It would be awesome if a user could get notifications when there's an event that brings points to him (that's for instance how the [q2a-badges](https://github.com/NoahY/q2a-badges) plugin works)

I don't know to which extent it could be feasible (I've seen that #690 suggests re-designing the point system; is it a prerequisite of this feature request?) or if it should be handled by a plugin, so feel free to tell me if I'm not posting at the correct location.

**Comment by svivian** [comment]
Generally, feature requests should be kept to the [Q2A Q&A](https://www.question2answer.org/qa/), thanks :)

Both of your requests can be achieved with [plugins](https://docs.question2answer.org/plugins/). The first would need a page plugin. In the plugin you can fetch all the options using `qa_opt()` and display the relevant ones. Makes more sense as a plugin than a core feature IMO, since you'd want your own content around the generated parts. Personally I have a "meta" question with all the points, so it can be easily updated by myself or other users if needed.

For the second, we are working on a notifications feature for the next version of Q2A, so there may be a way to hook into that for extra notifications.
