### ISSUE TITLE
To Much Spam In Question2Answer

### ISSUE THREAD

**Issue by Khankharor** [q2a/question2answer#775]
Dear Sir,
             I Inform U That In Question2Answer Script Lot Of Spam Is Made.
Spamer Bypass recaptcha Kindly Make An Strong Solution For This Problem

**Comment by QROkes** [comment]
I made these two Anti-Spam plugins, maybe you should give it a try:

Block some domains and check StopForumSpam API:
https://gist.github.com/QROkes/38845477e4f4674cb5a78d48939214a0

And this check posted content in Akismet, you need an Akismet-Key and also it only check posted content from users with less than "xx" points, you need to enter this two values in your code in order to get it to work:
https://gist.github.com/QROkes/bcf30838339aa2e8f188f290092ba21d

At least for me, it really solved the SPAM problem.

**Comment by svivian** [comment]
Closing this as there are a few other issues around the same topic. I'll look into some solutions when I can.
