### ISSUE TITLE
Google Captcha Bypass

### ISSUE THREAD

**Issue by thierryzoller** [q2a/question2answer#783]
I have noticed many fake registrations bypassing both the google captcha _and_ confirming their email addresses.

Any one else notices?

**Comment by jasdevmoun** [comment]
Not able to bypass on my website...

**Comment by Anton-V-K** [comment]
I confirm that reCaptcha doesn't block all bots. I see a constant flow of registered users with confirmed mails coming to my site, which are like bots seeking for something (probably trying to hack into the site).
I believe, reCaptcha does block some of them, but apparently few of them are "smart" enough to bypass it.

**Comment by thierryzoller** [comment]
I saw a number of accounts being registered, emails confirmed then staying dormant just to post Spam a few days later.

**Comment by Anton-V-K** [comment]
There is free premium plugin https://github.com/q2apro/q2apro-stop-spam (the reference was found in [the discussion at the Q2A site](https://www.question2answer.org/qa/70308/premium-plugin-nospam-gyzgyn?show=77038#c77038)).

Bot accounts on my site don't post anything. So it's still unclear what is the goal of their registration :)

**Comment by QROkes** [comment]
I made these two Anti-Spam plugins, maybe you should give it a try:

Block some domains and check StopForumSpam API:
https://gist.github.com/QROkes/38845477e4f4674cb5a78d48939214a0

And this check posted content in Akismet, you need an Akismet-Key and also it only check posted content from users with less than "xx" points, you need to enter this two values in your code in order to get it to work:
https://gist.github.com/QROkes/bcf30838339aa2e8f188f290092ba21d

At least for me, it really solved the SPAM problem.

**Comment by svivian** [comment]
As far as I can tell based on server logs, the accounts getting past the reCAPTCHA are not bots. They are using real browsers and loading the web page as a real user would. There are services out there where you can pay someone a few cents to keep filling out these forms.

Closing this as there are a few other issues around the same topic, but I'll look into some solutions when I can.

**Comment by thierryzoller** [comment]
A bit of feedback, the amount has increased tremedously. Hard to manually moderate.
