### ISSUE TITLE
Mobile friendly error in snowflat theme.   

### ISSUE THREAD

**Issue by farhanmonsurfahim** [q2a/question2answer#815]
So many mobile friendly errors in snowflat theme. 
More details here https://www.question2answer.org/qa/78542/how-to-fix-mobile-friendly-errors-in-snowflat-theme

none of this answer working.
please scott do something.
my search ranking also dropping.

**Comment by svivian** [comment]
The "errors" are due to the sidebar being off-screen. But it's fine for mobiles because it can be displayed using the < button. The tool is pretty unreliable because it works on some pages and not on others, even though the layout is the same.

If you really must please the tool there is an answer [here](https://www.question2answer.org/qa/78542/how-to-fix-mobile-friendly-errors-in-snowflat-theme?show=80697#a80697) you can implement.
