### ISSUE TITLE
All registered users can choose the answer as the best

### ISSUE THREAD

**Issue by Evgenivich** [q2a/question2answer#818]
I think it is wrong that all registered users can choose the answer as the best, as there can simply be cheating on bad answers. It seems to me that only the user who asked the question can choose the best answer, this will be the right thing.
If the user who asked the question within three months did not choose the best answer, then the system itself should put to the vote all participants for a better answer.
Maybe the person who asked the question will not return for an answer, this should be referred to experts.
And ate everyone will have the opportunity to choose the best answer, there will be a lot of not the truth, and fake answers that do not correspond to reality.

**Comment by phy25** [comment]
I have no idea why you think it works in this way:

> I think it is wrong that all registered users can choose the answer as the best, as there can simply be cheating on bad answers.

The actual setting there at YOUR_Q2A_INSTANCE/admin/permissions is "registered user with enough points" with a value that you can configure. You can also configure it so that only admin can choose the answer as the best.

Also I believe the question author can always choose the best answer regardless of your permission settings.

**Comment by svivian** [comment]
The best answer cannot be selected by any user. If you think you've found a bug where this is the case please provide more details, showing under what conditions it occurs. Thanks.
