### ISSUE TITLE
Please create a unique value of homepage and category for $template variable

### ISSUE THREAD

**Issue by teddydoors** [q2a/question2answer#825]
So far, we have these values for $template variable: 'activity', 'categories', 'custom', 'feedback', 'qa', 'question', 'questions', 'hot', 'search', 'tag',  'tags', 'unanswered'

I'm so mad that I would like to display something only on category pages, but there is NO unique value for category.

Again, the closest thing is "qa". But "qa" is also the homepage !!!!!!!!!!!!!!

I don't want to display on homepage. I just want on category page!!

In another event, I would like to display on homepage only, but it will show on category pages too.

**Comment by svivian** [comment]
This is not easy to achieve because the *template* is not exactly the same as what content is shown. The 'qa' template is for "recent questions and answers" but it doesn't matter whether that's all questions or just from one category. We also have different category pages under the 'questions' template (e.g. `example.com/questions/mycategory`).

One option is to check is `$content['categoryids']` is empty or not. If it's empty you are not on a category page. If it has elements then you are on a category page.
