### ISSUE TITLE
Refill event streams not work error undefined?

### ISSUE THREAD

**Issue by yerbol89** [q2a/question2answer#90]
In stats page Database clean-up operations not work Refill event streams
Error undefined.
https://www.youtube.com/watch?v=bOPm5We3kGI

**Comment by yerbol89** [comment]
@svivian 
https://www.youtube.com/watch?v=PnO86-Q80xc

**Comment by pupi1985** [comment]
You seem to be getting an error in a SQL query. You could take a look at your web server's log file as Q2A logs the failing SQL queries there.

Having said that, you are using MariaDB instead of MySQL. MariaDB **is not supported**. Anyway, I'd recommend you to provide the failing query as it **might** still be a bug there, regardless of the DBMS used.
