### ISSUE TITLE
Which branch to use?

### ISSUE THREAD

**Issue by GarfieldsPipe** [q2a/question2answer#929]
The current situation is kind of a mess. There are 3 relevant branches: dev, bugfix and master. Each of those branches has a lot of fixes that the other branches don't have, though. For example, the main branch (dev) doesn't have this bugfix: https://github.com/q2a/question2answer/commit/64725d84729873fa2ce5853931a4412364ae5aeb
And there are a ton of these examples for each of those branches.

**Comment by pupi1985** [comment]
The "main" branch is master (not dev), which is the stable version. Bugfix branch has the next patch version and the dev branch has the next minor version.

Regarding the only example you shared, I'd say it makes sense for the bugfix branch to have more bugfixes than master (until the exact moment in time it is merged to master).

If you have any suggestions to improve the workflow, please, write it down so that the official development team is able to provide a reply. Thanks.
